# Assignment 9 - NumPy

Name - Suryansh Tiwari

## Task 1: Creating NumPy Arrays

In [1]:
import numpy as np 

arr1 = np.arange(1, 11)
arr2 = np.arange(1, 10).reshape(3, 3)
arr3 = np.array([10, 20, 30, 40, 50])

print("arr1:",arr1)
print("Shape:", arr1.shape)
print("Data Type:", arr1.dtype)

print("\narr2:\n", arr2)
print("Shape:", arr2.shape)
print("Data Type:", arr2.dtype)

print("\narr3:", arr3)
print("Shape:", arr3.shape)
print("Data Type:", arr3.dtype)

arr1: [ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Data Type: int64

arr2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Data Type: int64

arr3: [10 20 30 40 50]
Shape: (5,)
Data Type: int64


## Task 2: Important Mathematical Operations

In [2]:
A = np.array([10, 20, 30, 40])
B = np.array([1, 2, 3, 4])

print("A + B =", A + B)
print("A - B =", A - B)
print("A * B =", A * B)
print("A / B =", A / B)
print("A ** 2 =", A ** 2)

print("np.add(A, B) =", np.add(A, B))
print("np.subtract(A, B) =", np.subtract(A, B))
print("np.multiply(A, B) =", np.multiply(A, B))
print("np.divide(A, B) =", np.divide(A, B))
print("np.power(A, 2) =", np.power(A, 2))

A + B = [11 22 33 44]
A - B = [ 9 18 27 36]
A * B = [ 10  40  90 160]
A / B = [10. 10. 10. 10.]
A ** 2 = [ 100  400  900 1600]
np.add(A, B) = [11 22 33 44]
np.subtract(A, B) = [ 9 18 27 36]
np.multiply(A, B) = [ 10  40  90 160]
np.divide(A, B) = [10. 10. 10. 10.]
np.power(A, 2) = [ 100  400  900 1600]


## Task 3: Important NumPy Mathematical Formulas

In [3]:
values = np.array([2, 4, 6, 8, 10])

print("values:", values)
print("Square root:", np.sqrt(values))
print("Exponential:", np.exp(values))
print("Natural log:", np.log(values))
print("Sum:", np.sum(values))
print("Cumulative sum:", np.cumsum(values))

values: [ 2  4  6  8 10]
Square root: [1.41421356 2.         2.44948974 2.82842712 3.16227766]
Exponential: [7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
Natural log: [0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]
Sum: 30
Cumulative sum: [ 2  6 12 20 30]


## Task 4: Aggregation Operations

In [4]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("data:\n", data)
print("Row-wise sum:", np.sum(data, axis=1))
print("Column-wise sum:", np.sum(data, axis=0))
print("Minimum value:", np.min(data))
print("Maximum value:", np.max(data))
print("Overall mean:", np.mean(data))

data:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Row-wise sum: [ 60 150 240]
Column-wise sum: [120 150 180]
Minimum value: 10
Maximum value: 90
Overall mean: 50.0


## Task 5: Statistical Operations

In [5]:
marks = np.array([78, 85, 90, 66, 72, 88, 95, 60])

print("Marks:", marks)
print("Mean:", np.mean(marks))
print("Median:", np.median(marks))
print("Standard Deviation:", np.std(marks))
print("Variance:", np.var(marks))
print("Minimum:", np.min(marks))
print("Maximum:", np.max(marks))
print("Range:", np.max(marks) - np.min(marks))

Marks: [78 85 90 66 72 88 95 60]
Mean: 79.25
Median: 81.5
Standard Deviation: 11.583932838203095
Variance: 134.1875
Minimum: 60
Maximum: 95
Range: 35


## Task 6: Percentiles & Sorting

In [6]:
sorted_marks = np.sort(marks)
print("Sorted Marks:", sorted_marks)
print("25th Percentile:", np.percentile(marks, 25))
print("50th Percentile (Median):", np.percentile(marks, 50))
print("75th Percentile:", np.percentile(marks, 75))

average_marks = np.mean(marks)
count_above_average = np.sum(marks > average_marks)
print("Average Marks:", average_marks)
print("Number of students above average:", count_above_average)

Sorted Marks: [60 66 72 78 85 88 90 95]
25th Percentile: 70.5
50th Percentile (Median): 81.5
75th Percentile: 88.5
Average Marks: 79.25
Number of students above average: 4


## Task 7: Mini Use Case - Sales Analysis

In [7]:
sales = np.array([1200, 1500, 900, 2000, 1800, 1700, 1600])

print("Sales:", sales)
print("Total Sales:", np.sum(sales))
print("Average Daily Sales:", np.mean(sales))
print("Highest sales day:", np.argmax(sales))
print("Lowest sales day:", np.argmin(sales))
print("Standard Deviation of Sales:", np.std(sales))

above_average_days = sales > np.mean(sales)
print("Days with above average sales:", sales[above_average_days])

Sales: [1200 1500  900 2000 1800 1700 1600]
Total Sales: 10700
Average Daily Sales: 1528.5714285714287
Highest sales day: 3
Lowest sales day: 2
Standard Deviation of Sales: 345.2298849598449
Days with above average sales: [2000 1800 1700 1600]
